'use strict';var hh=function(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||Ia,e=d.document,f=a.nonce||Ue(d);f&&!a.nonce&&(a.nonce=f);if("help"==a.flow){var g=Ja("document.location.href",d);!a.helpCenterContext&&g&&(a.helpCenterContext=g.substring(0,1200));g=!0;if(b&&JSON&&JSON.stringify){var h=JSON.stringify(b);(g=1200>=h.length)&&(a.psdJson=h)}g||(b={invalidPsd:!0})}b=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.serverUri||"//www.google.com/tools/feedback";if(g=d.GOOGLE_FEEDBACK_START)g.apply(d,b);
else{d=c+"/load.js?";for(var m in a)b=a[m],null==b||Oa(b)||(d+=encodeURIComponent(m)+"="+encodeURIComponent(b)+"&");a=dg(Uf(e),"SCRIPT");f&&a.setAttribute("nonce",f);Ve(a,fg(d));e.body.appendChild(a)}};v("userfeedback.api.startFeedback",hh);var ih=function(){this.j=this.h=this.u=this.modelName=this.l=this.g=this.dd="";this.C=this.o=this.m=!1};var jh=chrome.i18n.getMessage("4163185390680253103"),kh=chrome.i18n.getMessage("492097680647953484"),lh=chrome.i18n.getMessage("2575016469622936324"),mh=chrome.i18n.getMessage("128276876460319075"),nh=chrome.i18n.getMessage("3326722026796849289"),oh=chrome.i18n.getMessage("1018984561488520517"),ph=chrome.i18n.getMessage("8205999658352447129"),qh=chrome.i18n.getMessage("5723583529370342957"),rh=chrome.i18n.getMessage("1550904064710828958"),sh=chrome.i18n.getMessage("5014364904504073524"),th=chrome.i18n.getMessage("2194670894476780934"),
uh=chrome.i18n.getMessage("6614468912728530636"),wh=chrome.i18n.getMessage("5910595154486533449"),xh=chrome.i18n.getMessage("5363086287710390513"),yh=chrome.i18n.getMessage("244647017322945605"),zh=chrome.i18n.getMessage("5375576275991472719"),Ah=chrome.i18n.getMessage("4592127349908255218"),Bh=chrome.i18n.getMessage("843316808366399491"),Ch=chrome.i18n.getMessage("5699813974548050528"),Dh=chrome.i18n.getMessage("8515148417333877999"),Eh=chrome.i18n.getMessage("1636686747687494376"),Fh=chrome.i18n.getMessage("4148300086676792937"),
Gh=chrome.i18n.getMessage("3219866268410307919"),Hh=chrome.i18n.getMessage("9211708838274008657"),Ih=chrome.i18n.getMessage("8706273405040403641"),Jh=chrome.i18n.getMessage("4756056595565370923"),Kh=chrome.i18n.getMessage("7876724262035435114"),Lh=chrome.i18n.getMessage("5485620192329479690"),Mh=chrome.i18n.getMessage("6963873398546068901"),Nh=chrome.i18n.getMessage("3567591856726172993"),Oh=chrome.i18n.getMessage("3239956785410157548");/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Ph={"* ARIA-CHECKED":!0,"* ARIA-COLCOUNT":!0,"* ARIA-COLINDEX":!0,"* ARIA-CONTROLS":!0,"* ARIA-DESCRIBEDBY":!0,"* ARIA-DISABLED":!0,"* ARIA-EXPANDED":!0,"* ARIA-GOOG-EDITABLE":!0,"* ARIA-HASPOPUP":!0,"* ARIA-HIDDEN":!0,"* ARIA-LABEL":!0,"* ARIA-LABELLEDBY":!0,"* ARIA-MULTILINE":!0,"* ARIA-MULTISELECTABLE":!0,"* ARIA-ORIENTATION":!0,"* ARIA-PLACEHOLDER":!0,"* ARIA-READONLY":!0,"* ARIA-REQUIRED":!0,"* ARIA-ROLEDESCRIPTION":!0,"* ARIA-ROWCOUNT":!0,"* ARIA-ROWINDEX":!0,"* ARIA-SELECTED":!0,"* ABBR":!0,
"* ACCEPT":!0,"* ACCESSKEY":!0,"* ALIGN":!0,"* ALT":!0,"* AUTOCOMPLETE":!0,"* AXIS":!0,"* BGCOLOR":!0,"* BORDER":!0,"* CELLPADDING":!0,"* CELLSPACING":!0,"* CHAROFF":!0,"* CHAR":!0,"* CHECKED":!0,"* CLEAR":!0,"* COLOR":!0,"* COLSPAN":!0,"* COLS":!0,"* COMPACT":!0,"* COORDS":!0,"* DATETIME":!0,"* DIR":!0,"* DISABLED":!0,"* ENCTYPE":!0,"* FACE":!0,"* FRAME":!0,"* HEIGHT":!0,"* HREFLANG":!0,"* HSPACE":!0,"* ISMAP":!0,"* LABEL":!0,"* LANG":!0,"* MAX":!0,"* MAXLENGTH":!0,"* METHOD":!0,"* MULTIPLE":!0,
"* NOHREF":!0,"* NOSHADE":!0,"* NOWRAP":!0,"* OPEN":!0,"* READONLY":!0,"* REQUIRED":!0,"* REL":!0,"* REV":!0,"* ROLE":!0,"* ROWSPAN":!0,"* ROWS":!0,"* RULES":!0,"* SCOPE":!0,"* SELECTED":!0,"* SHAPE":!0,"* SIZE":!0,"* SPAN":!0,"* START":!0,"* SUMMARY":!0,"* TABINDEX":!0,"* TITLE":!0,"* TYPE":!0,"* VALIGN":!0,"* VALUE":!0,"* VSPACE":!0,"* WIDTH":!0},Qh={"* USEMAP":!0,"* ACTION":!0,"* CITE":!0,"* HREF":!0,"* LONGDESC":!0,"* SRC":!0,"LINK HREF":!0,"* FOR":!0,"* HEADERS":!0,"* NAME":!0,"A TARGET":!0,
"* CLASS":!0,"* ID":!0,"* STYLE":!0};var Rh={};
function Sh(a){if(of&&!Lf(9))return[0,0,0,0];var b=Rh.hasOwnProperty(a)?Rh[a]:null;if(b)return b;65536<Object.keys(Rh).length&&(Rh={});var c=[0,0,0,0];b=Th(a,/\\[0-9A-Fa-f]{6}\s?/g);b=Th(b,/\\[0-9A-Fa-f]{1,5}\s/g);b=Th(b,/\\./g);b=b.replace(/:not\(([^\)]*)\)/g,"     $1 ");b=b.replace(/{[^]*/gm,"");b=Uh(b,c,/(\[[^\]]+\])/g,2);b=Uh(b,c,/(#[^\#\s\+>~\.\[:]+)/g,1);b=Uh(b,c,/(\.[^\s\+>~\.\[:]+)/g,2);b=Uh(b,c,/(::[^\s\+>~\.\[:]+|:first-line|:first-letter|:before|:after)/gi,3);b=Uh(b,c,/(:[\w-]+\([^\)]*\))/gi,2);
b=Uh(b,c,/(:[^\s\+>~\.\[:]+)/g,2);b=b.replace(/[\*\s\+>~]/g," ");b=b.replace(/[#\.]/g," ");Uh(b,c,/([^\s\+>~\.\[:]+)/g,3);b=c;return Rh[a]=b}function Uh(a,b,c,d){return a.replace(c,function(e){b[d]+=1;return Array(e.length+1).join(" ")})}function Th(a,b){return a.replace(b,function(c){return Array(c.length+1).join("A")})};var Vh={rgb:!0,rgba:!0,alpha:!0,rect:!0,image:!0,"linear-gradient":!0,"radial-gradient":!0,"repeating-linear-gradient":!0,"repeating-radial-gradient":!0,"cubic-bezier":!0,matrix:!0,perspective:!0,rotate:!0,rotate3d:!0,rotatex:!0,rotatey:!0,steps:!0,rotatez:!0,scale:!0,scale3d:!0,scalex:!0,scaley:!0,scalez:!0,skew:!0,skewx:!0,skewy:!0,translate:!0,translate3d:!0,translatex:!0,translatey:!0,translatez:!0},Wh=/[\n\f\r"'()*<>]/g,Xh={"\n":"%0a","\f":"%0c","\r":"%0d",'"':"%22","'":"%27","(":"%28",")":"%29",
"*":"%2a","<":"%3c",">":"%3e"};function Yh(a){return Xh[a]}
var Zh=function(a,b,c){b=Pc(b);if(""==b)return null;if(0==Qc("url(",b.substr(0,4))){if(!b.endsWith(")")||1<(b?b.split("(").length-1:0)||1<(b?b.split(")").length-1:0)||!c)a=null;else{a:{b=b.substring(4,b.length-1);for(var d=0;2>d;d++){var e="\"'".charAt(d);if(b.charAt(0)==e&&b.charAt(b.length-1)==e){b=b.substring(1,b.length-1);break a}}}a=c?(a=c(b,a))&&"about:invalid#zClosurez"!=ne(a)?'url("'+ne(a).replace(Wh,Yh)+'")':null:null}return a}if(0<b.indexOf("(")){if(/"|'/.test(b))return null;for(a=/([\-\w]+)\(/g;c=
a.exec(b);)if(!(c[1].toLowerCase()in Vh))return null}return b};function $h(a,b){a=Ia[a];return a&&a.prototype?(b=Object.getOwnPropertyDescriptor(a.prototype,b))&&b.get||null:null}function ai(a,b){return(a=Ia[a])&&a.prototype&&a.prototype[b]||null}
var bi=$h("Element","attributes")||$h("Node","attributes"),ci=ai("Element","hasAttribute"),di=ai("Element","getAttribute"),ei=ai("Element","setAttribute"),fi=ai("Element","removeAttribute"),gi=ai("Element","getElementsByTagName"),hi=ai("Element","matches")||ai("Element","msMatchesSelector"),ii=$h("Node","nodeName"),ji=$h("Node","nodeType"),ki=$h("Node","parentNode"),li=$h("HTMLElement","style")||$h("Element","style"),mi=$h("HTMLStyleElement","sheet"),ni=ai("CSSStyleDeclaration","getPropertyValue"),
oi=ai("CSSStyleDeclaration","setProperty");function pi(a,b,c,d){if(a)return a.apply(b);a=b[c];if(!d(a))throw Error("Clobbering detected");return a}function qi(a,b,c,d){if(a)return a.apply(b,d);if(of&&10>document.documentMode){if(!b[c].call)throw Error("IE Clobbering detected");}else if("function"!=typeof b[c])throw Error("Clobbering detected");return b[c].apply(b,d)}function ri(a){return pi(bi,a,"attributes",function(b){return b instanceof NamedNodeMap})}
function si(a,b,c){try{qi(ei,a,"setAttribute",[b,c])}catch(d){if(-1==d.message.indexOf("A security problem occurred"))throw d;}}function ti(a){ui(a);return pi(li,a,"style",function(b){return b instanceof CSSStyleDeclaration})}function ui(a){if(!(a instanceof HTMLElement))throw Error("Not an HTMLElement");}function vi(a){ui(a);return pi(mi,a,"sheet",function(b){return b instanceof CSSStyleSheet})}function wi(a){return pi(ii,a,"nodeName",function(b){return"string"==typeof b})}
function xi(a){return pi(ji,a,"nodeType",function(b){return"number"==typeof b})}function yi(a){return pi(ki,a,"parentNode",function(b){return!(b&&"string"==typeof b.name&&b.name&&"parentnode"==b.name.toLowerCase())})}function zi(a,b){return qi(ni,a,a.getPropertyValue?"getPropertyValue":"getAttribute",[b])||""}function Ai(a,b,c){qi(oi,a,a.setProperty?"setProperty":"setAttribute",[b,c])};var Bi=of&&10>document.documentMode?null:/\s*([^\s'",]+[^'",]*(('([^'\r\n\f\\]|\\[^])*')|("([^"\r\n\f\\]|\\[^])*")|[^'",])*)/g,Ci={"-webkit-border-horizontal-spacing":!0,"-webkit-border-vertical-spacing":!0},Fi=function(a,b,c){var d=[];a=Di(tc(a.cssRules));Yb(a,function(e){if(b&&!/[a-zA-Z][\w-:\.]*/.test(b))throw Error("Invalid container id");if(!(b&&of&&10==document.documentMode&&/\\['"]/.test(e.selectorText))){var f=b?e.selectorText.replace(Bi,"#"+b+" $1"):e.selectorText,g=d.push;e=Ei(e.style,c);
if(-1!=f.indexOf("<"))throw Error("Selector does not allow '<', got: "+f);var h=f.replace(/('|")((?!\1)[^\r\n\f\\]|\\[\s\S])*\1/g,"");if(!/^[-_a-zA-Z0-9#.:* ,>+~[\]()=^$|]+$/.test(h))throw Error("Selector allows only [-_a-zA-Z0-9#.:* ,>+~[\\]()=^$|] and strings, got: "+f);a:{for(var m={"(":")","[":"]"},p=[],t=0;t<h.length;t++){var y=h[t];if(m[y])p.push(m[y]);else if(qd(m,y)&&p.pop()!=y){h=!1;break a}}h=0==p.length}if(!h)throw Error("() and [] in selector must be balanced, got: "+f);if(!(e instanceof
ue)){h="";for(var A in e)if(Object.prototype.hasOwnProperty.call(e,A)){if(!/^[-_a-zA-Z0-9]+$/.test(A))throw Error("Name allows only [-_a-zA-Z0-9], got: "+A);m=e[A];null!=m&&(m=Array.isArray(m)?bc(m,ye).join(" "):ye(m),h+=A+":"+m+";")}e=h?new ue(h,te):we}f=f+"{"+ve(e).replace(/</g,"\\3C ")+"}";g.call(d,new Ge(f,Fe))}});return Ie(d)},Di=function(a){return ac(a,function(b){return b instanceof CSSStyleRule||b.type==CSSRule.STYLE_RULE})},Hi=function(a,b,c){a=Gi("<style>"+a+"</style>");return null==a||
null==a.sheet?Je:Fi(a.sheet,void 0!=b?b:null,c)},Gi=function(a){if(of&&!Lf(10)||"function"!=typeof Ia.DOMParser)return null;a=Ne("<html><head></head><body>"+a+"</body></html>",null);return(new DOMParser).parseFromString(Me(a),"text/html").body.children[0]},Ei=function(a,b){if(!a)return we;var c=document.createElement("div").style,d=Ii(a);Yb(d,function(e){var f=rf&&e in Ci?e:e.replace(/^-(?:apple|css|epub|khtml|moz|mso?|o|rim|wap|webkit|xv)-(?=[a-z])/i,"");Mc(f,"--")||Mc(f,"var")||(e=zi(a,e),e=Zh(f,
e,b),null!=e&&Ai(c,f,e))});return new ue(c.cssText||"",te)},Ki=function(a){var b=Array.from(qi(gi,a,"getElementsByTagName",["STYLE"])),c=Lc(b,function(e){return tc(vi(e).cssRules)});c=Di(c);c.sort(function(e,f){e=Sh(e.selectorText);a:{f=Sh(f.selectorText);for(var g=Cc,h=Math.min(e.length,f.length),m=0;m<h;m++){var p=g(e[m],f[m]);if(0!=p){e=p;break a}}e=Cc(e.length,f.length)}return-e});a=document.createTreeWalker(a,NodeFilter.SHOW_ELEMENT,null,!1);for(var d;d=a.nextNode();)Yb(c,function(e){qi(hi,d,
d.matches?"matches":"msMatchesSelector",[e.selectorText])&&e.style&&Ji(d,e.style)});Yb(b,bg)},Ji=function(a,b){var c=Ii(a.style),d=Ii(b);Yb(d,function(e){if(!(0<=c.indexOf(e))){var f=zi(b,e);Ai(a.style,e,f)}})},Ii=function(a){Na(a)?a=tc(a):(a=od(a),oc(a,"cssText"));return a};var Pi="undefined"!=typeof WeakMap&&-1!=WeakMap.toString().indexOf("[native code]"),Qi=0,Ri=function(){this.j=[];this.h=[];this.g="data-elementweakmap-index-"+Qi++};Ri.prototype.set=function(a,b){if(qi(ci,a,"hasAttribute",[this.g])){var c=parseInt(qi(di,a,"getAttribute",[this.g])||null,10);this.h[c]=b}else c=this.h.push(b)-1,si(a,this.g,c.toString()),this.j.push(a);return this};
Ri.prototype.get=function(a){if(qi(ci,a,"hasAttribute",[this.g]))return a=parseInt(qi(di,a,"getAttribute",[this.g])||null,10),this.h[a]};Ri.prototype.clear=function(){this.j.forEach(function(a){qi(fi,a,"removeAttribute",[this.g])},this);this.j=[];this.h=[]};var Si=Yg("goog.html.sanitizer.SafeDomTreeProcessor"),Ti=!of||10<=Number(Of),Ui=!of||null==document.documentMode,Vi=function(){};var Wi={APPLET:!0,AUDIO:!0,BASE:!0,BGSOUND:!0,EMBED:!0,FORM:!0,IFRAME:!0,ISINDEX:!0,KEYGEN:!0,LAYER:!0,LINK:!0,META:!0,OBJECT:!0,SCRIPT:!0,SVG:!0,STYLE:!0,TEMPLATE:!0,VIDEO:!0};var Xi={A:!0,ABBR:!0,ACRONYM:!0,ADDRESS:!0,AREA:!0,ARTICLE:!0,ASIDE:!0,B:!0,BDI:!0,BDO:!0,BIG:!0,BLOCKQUOTE:!0,BR:!0,BUTTON:!0,CAPTION:!0,CENTER:!0,CITE:!0,CODE:!0,COL:!0,COLGROUP:!0,DATA:!0,DATALIST:!0,DD:!0,DEL:!0,DETAILS:!0,DFN:!0,DIALOG:!0,DIR:!0,DIV:!0,DL:!0,DT:!0,EM:!0,FIELDSET:!0,FIGCAPTION:!0,FIGURE:!0,FONT:!0,FOOTER:!0,FORM:!0,H1:!0,H2:!0,H3:!0,H4:!0,H5:!0,H6:!0,HEADER:!0,HGROUP:!0,HR:!0,I:!0,IMG:!0,INPUT:!0,INS:!0,KBD:!0,LABEL:!0,LEGEND:!0,LI:!0,MAIN:!0,MAP:!0,MARK:!0,MENU:!0,METER:!0,NAV:!0,
NOSCRIPT:!0,OL:!0,OPTGROUP:!0,OPTION:!0,OUTPUT:!0,P:!0,PRE:!0,PROGRESS:!0,Q:!0,S:!0,SAMP:!0,SECTION:!0,SELECT:!0,SMALL:!0,SOURCE:!0,SPAN:!0,STRIKE:!0,STRONG:!0,STYLE:!0,SUB:!0,SUMMARY:!0,SUP:!0,TABLE:!0,TBODY:!0,TD:!0,TEXTAREA:!0,TFOOT:!0,TH:!0,THEAD:!0,TIME:!0,TR:!0,TT:!0,U:!0,UL:!0,VAR:!0,WBR:!0};var Yi={"ANNOTATION-XML":!0,"COLOR-PROFILE":!0,"FONT-FACE":!0,"FONT-FACE-SRC":!0,"FONT-FACE-URI":!0,"FONT-FACE-FORMAT":!0,"FONT-FACE-NAME":!0,"MISSING-GLYPH":!0},bj=function(a){a=a||new Zi;$i(a);this.g=ud(a.g);this.m=ud(a.D);this.h=ud(a.F);this.u=a.C;Yb(a.H,function(b){if(!Mc(b,"data-"))throw new Tb('Only "data-" attributes allowed, got: %s.',[b]);if(Mc(b,"data-sanitizer-"))throw new Tb('Attributes with "%s" prefix are not allowed, got: %s.',["data-sanitizer-",b]);this.g["* "+b.toUpperCase()]=aj},
this);Yb(a.G,function(b){b=b.toUpperCase();if(-1==b.indexOf("-")||Yi[b])throw new Tb("Only valid custom element tag names allowed, got: %s.",[b]);this.h[b]=!0},this);this.C=a.j;this.l=a.u;this.j=null;this.o=a.o};Za(bj,Vi);
var cj=function(a){return function(b,c){return(b=a(Pc(b),c))&&"about:invalid#zClosurez"!=ne(b)?ne(b):null}},Zi=function(){this.g={};Yb([Ph,Qh],function(a){Yb(od(a),function(b){this.g[b]=aj},this)},this);this.h={};this.H=[];this.G=[];this.D=ud(Wi);this.F=ud(Xi);this.C=!1;this.O=se;this.M=this.m=this.J=this.j=Id;this.u=null;this.l=this.o=!1},dj=function(a,b){return function(c,d,e,f){c=a(c,d,e,f);return null==c?null:b(c,d,e,f)}},ej=function(a,b,c,d){a[c]&&!b[c]&&(a[c]=dj(a[c],d))};Zi.prototype.fa=function(){return new bj(this)};
var $i=function(a){if(a.l)throw Error("HtmlSanitizer.Builder.build() can only be used once.");ej(a.g,a.h,"* USEMAP",fj);var b=cj(a.O);Yb(["* ACTION","* CITE","* HREF"],function(d){ej(this.g,this.h,d,b)},a);var c=cj(a.j);Yb(["* LONGDESC","* SRC","LINK HREF"],function(d){ej(this.g,this.h,d,c)},a);Yb(["* FOR","* HEADERS","* NAME"],function(d){ej(this.g,this.h,d,Xa(gj,this.J))},a);ej(a.g,a.h,"A TARGET",Xa(hj,["_blank","_self"]));ej(a.g,a.h,"* CLASS",Xa(ij,a.m));ej(a.g,a.h,"* ID",Xa(jj,a.m));ej(a.g,a.h,
"* STYLE",Xa(a.M,c));a.l=!0},kj=function(a,b){a||(a="*");return(a+" "+b).toUpperCase()},aj=function(a){return Pc(a)},hj=function(a,b){b=Pc(b);return ic(a,b.toLowerCase())?b:null},fj=function(a){return(a=Pc(a))&&"#"==a.charAt(0)?a:null},gj=function(a,b,c){return a(Pc(b),c)},ij=function(a,b,c){b=b.split(/(?:\s+)/);for(var d=[],e=0;e<b.length;e++){var f=a(b[e],c);f&&d.push(f)}return 0==d.length?null:d.join(" ")},jj=function(a,b,c){return a(Pc(b),c)},lj=function(a,b){var c=b.data;(b=yi(b))&&"style"==
wi(b).toLowerCase()&&!("STYLE"in a.m)&&"STYLE"in a.h&&(c=He(Hi(c,a.j,Wa(function(d,e){return this.C(d,{YT:e})},a))));return document.createTextNode(c)},mj=function(a){var b=(new Zi).fa();var c=!("STYLE"in b.m)&&"STYLE"in b.h;c="*"==b.l&&c?"sanitizer-"+bf():b.l;b.j=c;if(Ti){c=a;if(Ti){a=$f(document,"SPAN");b.j&&"*"==b.l&&(a.id=b.j);b.o&&(c=Gi("<div>"+c+"</div>"),Ki(c),c=c.innerHTML);c=Ne(c,null);var d=document.createElement("template");if(Ui&&"content"in d)Se(d,c),d=d.content;else{var e=document.implementation.createHTMLDocument("x");
d=e.body;Se(e.body,c)}c=document.createTreeWalker(d,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT,null,!1);for(d=Pi?new WeakMap:new Ri;e=c.nextNode();){c:{var f=b;var g=e;var h=xi(g);switch(h){case 3:g=lj(f,g);break c;case 1:h=g;1==xi(h)||Ub("Expected Node of type Element but got Node of type %s",xi(h));g=f;f=h;if("TEMPLATE"==wi(f).toUpperCase())g=null;else{h=wi(f).toUpperCase();if(h in g.m)var m=null;else g.h[h]?m=document.createElement(h):(m=$f(document,"SPAN"),g.u&&si(m,"data-sanitizer-original-tag",
h.toLowerCase()));if(m){var p=m,t=ri(f);if(null!=t)for(var y=0;h=t[y];y++)if(h.specified){var A=g;var B=f,H=h,Q=H.name;if(Mc(Q,"data-sanitizer-"))A=null;else{var ea=wi(B);H=H.value;var eb={tagName:Pc(ea).toLowerCase(),attributeName:Pc(Q).toLowerCase()},$b={Uw:void 0};"style"==eb.attributeName&&($b.Uw=ti(B));B=kj(ea,Q);B in A.g?(A=A.g[B],A=A(H,eb,$b)):(Q=kj(null,Q),Q in A.g?(A=A.g[Q],A=A(H,eb,$b)):A=null)}null!==A&&si(p,h.name,A)}g=m}else g=null}break c;default:ah(Si,"Dropping unknown node type: "+
h),g=null}}if(g){if(1==xi(g)&&d.set(e,g),e=yi(e),f=!1,e)h=xi(e),m=wi(e).toLowerCase(),p=yi(e),11!=h||p?"body"==m&&p&&(h=yi(p))&&!yi(h)&&(f=!0):f=!0,h=null,f||!e?h=a:1==xi(e)&&(h=d.get(e)),h.content&&(h=h.content),h.appendChild(g)}else ag(e)}d.clear&&d.clear();b=a}else b=$f(document,"SPAN");0<ri(b).length&&(a=$f(document,"SPAN"),a.appendChild(b),b=a);b=(new XMLSerializer).serializeToString(b);b=b.slice(b.indexOf(">")+1,b.lastIndexOf("</"))}else b="";return Ne(b,null)};if("undefined"!=typeof angular){var nj=angular.module("chrome_18n",[]);chrome.runtime&&chrome.runtime.getManifest&&chrome.runtime.getManifest().default_locale&&nj.directive("angularMessage",function(){return{restrict:"E",replace:!0,controller:["$scope",function(a){var b=this;this.fl=this.Ch=null;a.dirForText=function(c){b.Ch||(b.Ch=chrome.i18n.getMessage("@@bidi_dir")||"ltr");b.fl||(b.fl=new dh("rtl"==b.Ch));var d=b.fl,e,f=e=0,g=!1;c=(c||"").split(Zd);for(var h=0;h<c.length;h++){var m=c[h];Xd.test(m)?
(e++,f++):Yd.test(m)?g=!0:Wd.test(m)?f++:$d.test(m)&&(g=!0)}e=0==f?g?1:0:.4<e/f?-1:1;return-1==(0==e?d.g:e)?"rtl":"ltr"}}],compile:function(a,b){b=b.key;var c=null,d=document.createElement("amr");b&&!b.match(/^\d+$/)&&(b=chrome.i18n.getMessage(b),null==b&&d.setAttribute("id","missing"));if(b){var e=chrome.i18n.getMessage(b+"_ph");c=[];if(null!=e)for(c=e.split("\ue000"),e=0;e<c.length;++e)c[e]=c[e].replace(/^{{(.*)}}$/,'<amrp dir="{{dirForText($1)}}">{{$1}}</amrp>');c=chrome.i18n.getMessage(b,c)}else d.setAttribute("r",
"nokey");c?Te(d,mj(c)):(d.setAttribute("tl","false"),Te(d,mj(a.html())));a.replaceWith(d)}}})};var pj=function(a,b){var c=this;this.o=b;this.g=a;this.g.top=a;this.C=[];this.l=!1;this.h=new ih;this.g.videoSmoothnessRatings=this.Zm(th,oh,ph,qh,rh,sh);this.g.videoQualityRatings=this.Zm(th,uh,wh,xh,yh,zh);this.g.audioQualityRatings=this.Zm(th,Ah,Bh,Ch,Dh,Eh);this.C=[{value:"Bug",desc:jh},{value:"FeatureRequest",desc:kh},{value:"MirroringQuality",desc:lh},{value:"Discovery",desc:mh},{value:"Other",desc:nh}];this.g.feedbackTypes=this.C;this.g.includeFineLogs=!0;this.g.feedbackType="Bug";this.g.sendFeedback=
this.IC.bind(this);this.g.cancel=this.Lw.bind(this);this.g.attachLogsClick=this.m.bind(this);this.g.viewLogs=this.F.bind(this);this.g.$watchGroup("videoSmoothness videoQuality audioQuality feedbackDescription comments feedbackType".split(" "),this.Ow.bind(this));this.g.sufficientFeedback=!1;this.g.$watch("attachLogs",this.m.bind(this));this.g.attachLogs=!0;this.u=bf();this.g.userEmail="";chrome.identity.getProfileUserInfo(function(d){c.g.userEmail=d.email;oj(c)});this.g.yourAnswerText=Oh;this.g.language=
chrome.i18n&&chrome.i18n.getUILanguage?chrome.i18n.getUILanguage():chrome.runtime.getManifest().default_locale;this.g.requestLogsInProgress=!1;this.g.mrVersion=chrome.runtime.getManifest().version};k=pj.prototype;k.Zm=function(a){for(var b=[],c=1;c<arguments.length;c++)b.push(new qj(c,arguments[c]));b.push(new qj(0,arguments[0]));return b};k.Lw=function(){this.g.feedbackDescription&&!confirm(Fh)||window.close()};
k.Ow=function(){var a=this.g.feedbackType;this.g.sufficientFeedback="MirroringQuality"==a?this.g.videoSmoothness||this.g.videoQuality||this.g.audioQuality||this.g.comments:"Discovery"==a?this.g.visibleInSetup||this.g.comments:!!this.g.feedbackDescription};
k.IC=function(){if(this.g.sufficientFeedback){var a=this.g.feedbackType,b="";"MirroringQuality"==a?(this.g.videoSmoothness&&(b+="\nVideo Smoothness: "+this.g.videoSmoothness),this.g.videoQuality&&(b+="\nVideo Quality: "+this.g.videoQuality),this.g.audioQuality&&(b+="\nAudio: "+this.g.audioQuality),this.g.projectedContentUrl&&(b+="\nProjected Content/URL: "+this.g.projectedContentUrl),this.g.comments&&(b+="\nComments: "+this.g.comments)):"Discovery"==a?(this.g.visibleInSetup&&(b+="\nChromecast Visible in Setup: "+
this.g.visibleInSetup),this.g.hasNetworkSoftware&&(b+="\nUsing VPN/proxy/firewall/NAS Software: "+this.g.hasNetworkSoftware),this.g.networkDescription&&(b+="\nNetwork Description: "+this.g.networkDescription),this.g.comments&&(b+="\nComments: "+this.g.comments)):b=this.g.feedbackDescription;a="Type: "+a+"\n\n"+b;this.g.sendDialogText=Gh;this.g.okButton=Nh;this.g.feedbackSent=!1;this.o.show({locals:{qU:this.g.feedbackSent,lW:this.g.sendDialogText,xB:this.g.okButton},scope:this.g,preserveScope:!0,bindToController:!0,
template:'<md-dialog id="feedback-confirmation"><md-dialog-content><div id="send-feedback-text">{{sendDialogText}}</div><md-dialog-actions><md-button class="md-raised md-primary"ng-disabled="!feedbackSent" ng-click="closeWindow()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',controller:this.j});this.Fr(a,Date.now())}};k.Fr=function(a,b){var c=Date.now();!this.g.requestLogsInProgress||5E3<c-b?rj(this,a):setTimeout(this.Fr.bind(this),1E3,a,b)};
var rj=function(a,b){var c=0,d=function(f,g,h){h?f(!0):(a.g.sendDialogText=Jh,oj(a),g(Error("Failed to send")))},e=chrome.declarativeWebRequest?"MrTeamfood":"MRStable";(new fh(function(){c++;return new Promise(function(f,g){var h=a.g.userEmail,m=a.h;f=d.bind(null,f,g);g=chrome.runtime.getManifest();hh({productId:85561,bucket:e,flow:"submit",serverUri:"https://www.google.com/tools/feedback",allowNonLoggedInFeedback:!0,locale:g.default_locale,enableAnonymousFeedback:!h,report:{description:b},callback:f},
{version:g.version,description:g.description,user_email:h||"NA",logs:m.dd||"NA",external_logs:m.g||"NA",device_model:m.modelName||"NA",receiver_version:m.u||"NA",dash_report_url:m.l||"NA",cast_device_counts:m.h,dial_device_counts:m.j,mirroring_service_enabled:m.m,native_cast_mrp_enabled:m.o,native_dial_mrp_enabled:m.C})})},1E4,4)).start().then(function(){Kb("MediaRouter.Ui.Action.Feedback");a.g.sendDialogText=Ih;a.g.feedbackSent=!0;oj(a)},function(){a.g.sendDialogText=Hh;a.g.feedbackSent=!0;oj(a)})};
pj.prototype.m=function(){var a=this;this.h=new ih;this.g.attachLogs&&(this.g.requestLogsInProgress=!0,chrome.runtime.sendMessage(new eh(this.u,"retrieve_log_data"),function(b){a.g.requestLogsInProgress=!1;a.h.dd=b.logs||"no extension";a.h.dd+="\n";a.h.dd+=b.mediaSinkServiceStatus||"no media sink service status from browser";a.h.dd+="\n";a.h.dd+=b.mediaRouterLogs||"no Media Router logs from the browser";b.castStreamingLogs&&(a.h.l=b.castStreamingLogs);b.castDeviceCounts&&(a.h.h=b.castDeviceCounts);
b.dialDeviceCounts&&(a.h.j=b.dialDeviceCounts);a.h.m=!!b.mirroringServiceEnabled;a.h.o=!!b.nativeCastMrpEnabled;a.h.C=!!b.nativeDialMrpEnabled;if(b=b.device)if(b.model&&(a.h.modelName=b.model),b.version&&(a.h.u=b.version),!a.l){var c=bf();a.l=!0;a.h.g=wb(b.ip,c,a.D.bind(a))}}))};
pj.prototype.F=function(){this.g.logs=this.h.dd;this.g.logsHeader=Kh;this.g.sendLogs=Lh;this.g.fineLogsWarning=Mh;this.g.okButton=Nh;this.o.show({locals:{ET:this.g.attachLogs,dd:this.g.logs,LU:this.g.includeFineLogs,pV:this.g.logsHeader,mW:this.g.sendLogs,rU:this.g.fineLogsWarning,xB:this.g.okButton},scope:this.g,preserveScope:!0,bindToController:!0,clickOutsideToClose:!0,template:'<md-dialog><md-dialog-content id="logs-dialog"><div class="subheading">{{logsHeader}}</div><div ng-show="includeFineLogs && attachLogs"id="feedback-fine-log-warning" class="informative">{{fineLogsWarning}}</div><pre>{{logs}}</pre><div class="send-logs"><md-checkbox type="checkbox" ng-model="attachLogs"ng-change="attachLogsClick()"><span>{{sendLogs}}</span></md-checkbox></div><md-dialog-actions><md-button class="md-raised md-primary"ng-click="closeDialog()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',
controller:this.j})};pj.prototype.D=function(a,b){this.l=!1;this.h.g="error"==a?"":b;this.g.attachLogs||(this.h.g="");oj(this)};var oj=function(a){a.g.$$phase||a.g.$apply()};pj.prototype.j=function(a,b){a.closeWindow=function(){window.close()};a.closeDialog=function(){b.hide()}};pj.prototype.j.$inject=["$scope","$mdDialog"];var qj=function(a,b){this.id=a;this.desc=b;this.text=0==a?b:a+" ("+b+")"};
angular.module("feedbackApp","chrome_18n material.components.button material.components.checkbox material.components.dialog material.components.input material.components.radioButton".split(" ")).controller("FeedbackCtrl",["$scope","$mdDialog",pj]);v("ng.safehtml.googSceHelper.isGoogHtmlType",function(a){return a&&a.fe?!0:!1});v("ng.safehtml.googSceHelper.isCOMPILED",function(){return!0});v("ng.safehtml.googSceHelper.unwrapAny",function(a){if(a instanceof be)return ce(a).toString();if(a instanceof Le)return Me(a).toString();if(a instanceof me)return ne(a);if(a instanceof ue)return ve(a);if(a instanceof Ud)return Vd(a).toString();throw Error();});
v("ng.safehtml.googSceHelper.unwrapGivenContext",function(a,b){if("html"==a)return Me(b).toString();if("resourceUrl"==a||"templateUrl"==a)return ce(b).toString();if("url"==a)return b instanceof be?ce(b).toString():ne(b);if("css"==a)return ve(b);if("js"==a)return Vd(b).toString();throw Error();});
